name:                haskalpaca
version:             0.1.0.0
github:              "robbiebarnhoorn/haskalpaca"
license:             BSD3
author:              "Robbie Barnhoorn"
maintainer:          "robbie.barnhoorn@gmail.com"
copyright:           "2020 Robbie Barnhoorn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/robbiebarnhoorn/haskalpaca#readme>

dependencies:
- aeson
- aeson-casing
- array
- base >= 4.7 && < 5
- bytestring
- Cabal
- containers
- lens
- lens-aeson
- pretty-simple
- text
- time
- utf8-string
- wreq

default-extensions:
- OverloadedStrings
- LambdaCase

library:
  source-dirs: src

executables:
  haskalpaca-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -haddock
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskalpaca

tests:
  haskalpaca-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -haddock
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskalpaca
